### ISSUE TITLE
IOError: File not open for writing

### ISSUE THREAD

**Issue by i3dcor** [jasoneppink/FluxVision#1]
I like your project but you missed to open for write _count_playlist_ file on _play_youtube.py_
then i got this error:
_Traceback (most recent call last):
  File "./play_youtube.py", line 88, in <module>
    count_playlist.write(str(value + 1))
IOError: File not open for writing_

I fixed it modifying line 88 of _play_youtube.py_ from:
  with open(abs_path + '.count_playlist') as count_playlist:
to:
  with open(abs_path + '.count_playlist', 'w' ) as count_playlist:

**Comment by jasoneppink** [comment]
Good catch. Thank you!
